name: Vue.js App CI/CD

on:
  push:
    branches:
      - production  # Trigger on push to the 'production' branch
  pull_request:
    branches:
      - production  # Trigger on PR to 'production' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run build command - this creates the dist folder
    - name: Build Vue.js app
      run: npm run build

    # Set up SSH for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Run the build directly on the server to update the dist folder
    - name: Run build on server
      run: |
        ssh -o StrictHostKeyChecking=no root@139.5.189.188 'cd /root/dashboardFrontend/monitor-frontend-new && npm install && npm run build'
