name: Vue.js App CI/CD

on:
  push:
    branches:
      - production  # Trigger on push to the 'production' branch
  pull_request:
    branches:
      - production  # Trigger on PR to 'production' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run build command - this creates the dist folder
    - name: Build Vue.js app
      run: |
        npm run build
        ls -al ./dist  # Ensure dist folder is generated and list its contents

    # Set up SSH for deployment to Test Server
    - name: Set up SSH for Test Server
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Test server's SSH key

    # Deploy dist folder to Test Server
    - name: Deploy dist folder to Test Server
      run: |

        # Copy the dist folder to the Test Server's /var/www/monitor-frontend
        scp -r ./dist/* root@139.5.189.188:/var/www/monitor-frontend/
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # Set up SSH for deployment to Production Server
    - name: Set up SSH for Production Server
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}  # Production server's SSH key

    # Deploy dist folder to Production Server
    - name: Deploy dist folder to Production Server
      run: |

        # Copy the dist folder to the Production Server's /var/www/monitor-frontend
        scp -r ./dist/* root@139.5.188.147:/var/www/monitor-frontend/
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
