name: Vue.js App CI/CD

on:
  push:
    branches:
      - production  # Trigger on push to the 'production' branch
  pull_request:
    branches:
      - production  # Trigger on PR to 'production' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run build command
    - name: Build Vue.js app
      run: npm run build

    # Set up SSH for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the private key in GitHub Secrets

    # Deploy to the server
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@139.5.189.188 'rm -rf /path/to/your/webroot/*'  # Clear the existing content
        scp -r ./dist/* root@139.5.189.188:/path/to/your/webroot/  # Copy the dist folder to the server
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
