name: Vue.js App CI/CD

on:
  push:
    branches:
      - production  # Trigger on push to the 'production' branch
  pull_request:
    branches:
      - production  # Trigger on PR to 'production' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run build command - this creates the dist folder
    - name: Build Vue.js app
      run: |
        npm run build
        ls -al ./dist  # Ensure dist folder is generated and list its contents

    # Set up SSH for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Deploy dist folder to the server
    - name: Deploy dist folder to server
      run: |
        # Remove old content in /var/www/monitor-frontend
        ssh -o StrictHostKeyChecking=no root@139.5.189.188 'rm -rf /var/www/monitor-frontend/*'

        # Copy the dist folder to /var/www/monitor-frontend
        scp -r ./dist/* root@139.5.189.188:/var/www/monitor-frontend/
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
